# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kayit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300)),
                ('soyad', models.CharField(max_length=300)),
                ('mail', models.CharField(max_length=300)),
                ('sifre', models.CharField(max_length=300)),
            ],
        ),
    ]
