# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApplication', '0002_kayit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kayit',
            new_name='Person',
        ),
    ]
